name: grid lab
favicon: null
layout_spectrum: 0
typography_spectrum: 0.76181
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#050505'
    - '#4c727d'
    - '#c06562'
    - '#881311'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
