name: grid lab
favicon: null
layout_spectrum: 0.99138
typography_spectrum: 0.6127818305976689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#232a01'
    - '#c6d9e9'
    - '#6b6d00'
    - '#7c8e78'
  brandStrength: 0.3125
  lightness: 0.6149129003752023
  saturation: 0.7289809193462133
  rhythmicContrast: 0.5
purpose: []
