name: grid lab
favicon: null
layout_spectrum: 0.98667
typography_spectrum: 0.10454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#050505'
    - '#4c727d'
    - '#c06562'
    - '#881311'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
